SELECT  ?person ?property ?textMatch ?score
WHERE {

    ?person a :Person .
    ?person ?property ?textMatch .
    
    (?textMatch ?score) <tag:stardog:api:property:textMatch> "Star*".
} ORDER BY desc(?score)